### ISSUE TITLE
Improving Bleach

### ISSUE THREAD

**Issue by markkerrigan** [YakovL/TiddlyThemes#2]
I am comparing line by line, but first I started with PageTemplate. In my version, I have some extra attributes. Are those necessary?

```
<div id='sidebarOptions' role='navigation' refresh='content' tiddler='SideBarOptions'></div>
<div id='sidebarTabs' role='complementary' refresh='content' force='true' tiddler='SideBarTabs'></div>
```

Also there is this line, which I have removed in my own version. Is it necessary?

```
<div class='clearAll'></div>
```

**Comment by markkerrigan** [comment]
# StyleSheet

This rule should be removed because it overrides the classes tiddlyLinkExisting and tiddlyLinkNonExisting.

```
#sidebarTabs .txtMainTab .tabContents li a { font-weight:bold; }
```

Consider removing or adjusting this rule because it interferes with the default way sidebar tabs look

```
#sidebarTabs .tabUnselected { border-bottom: none;padding-bottom:3px;}
#sidebarTabs .tabSelected{padding-bottom:3px;}
```

Not sure what these rules are for?

```
#contentWrapper { height:1%; }
#header { height: 1%; }
.clearAll { clear: both; }
```

Typo, but maybe this should be different than Trebuchet MS?

```
.siteTitle { font-family: 'Trebuchet MS', sans-serif; }
```

**Comment by YakovL** [comment]
Hi Mark,

- `role` attributes in PageTemplate: they probably improve semantical structure of the page (may affect screen reader flow, for instance), but it's difficult to say how useful/correct/specific they are, accessibility is a complicated topic, and I don't have enough expertise yet. I don't think they are important (as accessibility is not consistent in TW anyway and requires ground-up considerations), but we can add them anyway
- `<div class='clearAll'></div>` prevents floating elements like images to float into the bottom padding. This doesn't make a graeat difference, but is a good practice. Here's an illustration (for a quick one, I've modified the tags pill):
  ![image](https://github.com/YakovL/TiddlyThemes/assets/1131924/3f06a1a5-cfc3-4cd1-91fb-96ad77c482fe)

- `rule should be removed` – agreed
- `Consider removing or adjusting this rule` – yeah, I'm going to improve tabs styles in 2.9.5, already started some experiments. Feel free to propose changes on the theme level, but just removing the padding is not a good option either:
  ![image](https://github.com/YakovL/TiddlyThemes/assets/1131924/6d4d04e7-c077-4c10-b568-02aeae4f94d5)

- `Not sure what these rules are for?` – I've covered `.clearAll { clear: both; }` above; as for the other two (`1%`), they don't make any sense indeed and can be removed.
  - What `#contentWrapper` may need is stretching it like `min-height: calc(100vh - 5.1em);`, but this is not enough to make the footer stick to the bottom, that requires additional restyling (using CSS grid) or restructuring (common container for `#sidebar` + `#displayArea`) and restyling (using CSS flex)
- `Typo` – indeed, the comma is missing; `maybe this should be different than Trebuchet MS?` – well, this is a matter of taste, to me it looks ok. What I agree with, though, is that using 3 families (`#contentWrapper: Lucida Grande, Tahoma, Arial, Helvetica, sans-serif`, `.siteTitle: 'Trebuchet MS', sans-serif`, `h1,h2,h3,h4,h5: Arial, Helvetica, sans-serif`) is hardly an adequate choice. I'd probably use the same family for `.siteTitle`, `h1,h2,h3,h4,h5`, and also [tiddler] `.title` (and put it into one rule); Trebuchet MS looks ok (see the screenshot below), but this way anybody can change it to whatever they like in just one line of code.
  ![image](https://github.com/YakovL/TiddlyThemes/assets/1131924/606fa8b6-0196-47ba-834c-619d40275771)

- I've also noticed that the search button hover adds invisible border and moves the content below it, so this should probably be overwritten.
  ![gid_demonstrating_the_issue](https://github.com/YakovL/TiddlyThemes/assets/1131924/c92d262f-3295-4dbf-9788-d682e70af4c5)
 - PS: Also, I'd remove the `.viewer table` thick border like I've removed it in the core already. I guess, the intention here was to make it less bright (`#888`) than the old core versions had it, but in 2.9.4 it's even lighter. Not to mention that the theme should utilize colors from ColorPalette (at least `#999` and other existing): otherwise it will work poorly with DarkModePlugin.

Feel free to open a PR with the changes we're discussing; I'll concentrate on the tabs styles in the core first.

**Comment by markkerrigan** [comment]
Summary. I will submit a PR with the changes so far. As far as the tabs go, if you already have ideas on how to improve the tabs look I will hold off. My main issue with the current way tabs look is there is ever so slight overlap with the padding. Bleach has this really subtle look, although in my version I changed much of the use of `#EF680E` to `#999`. So it doesn't look like Bleach anymore. But it is one of the few themes that uses a center fixed width layout.

### Remove

```
#sidebarTabs .txtMainTab .tabContents li a { font-weight:bold; }
#contentWrapper { height:1%; }
#header { height: 1%; }
```

### Correct Typo

Will standardize font-family.

```
.siteTitle { font-family: 'Trebuchet MS', sans-serif; }
```

### Add

Adding this fixes the hover border issue.

```
#sidebarOptions a { border:1px solid #fff; }
```

**Comment by YakovL** [comment]
Sounds great!

**Comment by YakovL** [comment]
Hi @markkerrigan , are you still planning to create a PR or should I commit the changes myself?

**Comment by markkerrigan** [comment]
No, it's OK you can commit the changes, I don't think I have the time at the moment to make a PR

**Comment by YakovL** [comment]
Right, I've committed these changes and some more
